#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#
#      routes:
#        - id: student-service
#          uri: lb://student-service
#          predicates:
#            - Path=/api/students,/api/students/**
#
#
#        - id: course-service
#          uri: lb://course-service
#          predicates:
#            - Path=/api/courses,/api/courses/**
#
#        - id: attendance-service
#          uri: lb://attendance-service
#          predicates:
#            - Path=/api/attendance,/api/attendance/**
#
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth,/api/auth/**
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,gateway
#  endpoint:
#    gateway:
#      enabled: true
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web.reactive.DispatcherHandler: DEBUG
#    reactor.netty.http.client: DEBUG
